# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true
    http_client:
        #default_options:
            #headers:
                #'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        scoped_clients:
            osm.client:
                base_uri: 'https://nominatim.openstreetmap.org/'
            gisg.client:
                base_uri: 'https://services.gisgraphy.com/'

            here.client: #needs an account
                base_uri: 'https://geocode.search.hereapi.com/v1/'
            google.client: #needs an account
                base_uri: 'https://maps.googleapis.com/maps/api/'
            esri.client: #needs an account
                base_uri: 'https://geocode-api.arcgis.com/arcgis/rest/services/World/GeocodeServer/'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
